### Load Processed Clause CSV file

In [1]:
import pandas as pd
import re

df = pd.read_csv("../data/processed/cuad_clauses.csv")
df.head()

,clause_text,clause_type
0,The term of this Agreement shall be ten (10)...,Highlight the parts (if any) of this contract ...
1,The term of this Agreement shall be ten (10)...,Highlight the parts (if any) of this contract ...
2,If Distributor comp...,Highlight the parts (if any) of this contract ...
3,This Agreement is to be construed according to...,Highlight the parts (if any) of this contract ...
4,The Distributor shall not order or ...,Highlight the parts (if any) of this contract ...

### Extracting clean clause names

In [2]:
def extract_clause_name(text):
    match = re.search(r'"(.*?)"', text)
    return match.group(1) if match else text

df["clean_clause"] = df["clause_type"].apply(extract_clause_name)

df[["clause_type", "clean_clause"]].head()

                                         clause_type     clean_clause
0  Highlight the parts (if any) of this contract ...   Effective Date
1  Highlight the parts (if any) of this contract ...  Expiration Date
2  Highlight the parts (if any) of this contract ...     Renewal Term
3  Highlight the parts (if any) of this contract ...    Governing Law
4  Highlight the parts (if any) of this contract ...      Exclusivity

In [9]:
df["clean_clause"].value_counts().head(41)

clean_clause
Governing Law                         434
Expiration Date                       412
Anti-Assignment                       373
Cap On Liability                      275
License Grant                         255
Audit Rights                          214
Termination For Convenience           183
Post-Termination Services             181
Exclusivity                           180
Document Name                         177
Renewal Term                          175
Revenue/Profit Sharing                165
Minimum Commitment                    164
Insurance                             163
Non-Transferable License              136
Ip Ownership Assignment               123
Change Of Control                     121
Effective Date                        120
Non-Compete                           118
Uncapped Liability                    111
Notice Period To Terminate Renewal    110
Parties                               107
Covenant Not To Sue                   100
Rofr/Rofo/Rofn                         85
Volume Restriction                     82
Competitive Restriction Exception      75
Warranty Duration                      74
Irrevocable Or Perpetual License       70
Liquidated Damages                     61
No-Solicit Of Employees                59
Affiliate License-Licensee             59
Joint Ip Ownership                     46
Non-Disparagement                      38
No-Solicit Of Customers                34
Third Party Beneficiary                32
Most Favored Nation                    27
Affiliate License-Licensor             23
Agreement Date                         18
Unlimited/All-You-Can-Eat-License      17
Price Restrictions                     15
Source Code Escrow                     13
Name: count, dtype: int64

### Risk Mapping

In [10]:
risk_map = {

    # 🔴 HIGH RISK — serious legal/financial exposure
    "Cap On Liability": "High",
    "Uncapped Liability": "High",
    "Termination For Convenience": "High",
    "Exclusivity": "High",
    "Non-Compete": "High",
    "Indemnification": "High",
    "Liquidated Damages": "High",
    "Covenant Not To Sue": "High",
    "Most Favored Nation": "High",
    "Ip Ownership Assignment": "High",
    "Joint Ip Ownership": "High",
    "Change Of Control": "High",
    "Competitive Restriction Exception": "High",
    "Volume Restriction": "High",

    # 🟡 MEDIUM RISK — cost, compliance, operations
    "Payment Terms": "Medium",
    "Revenue/Profit Sharing": "Medium",
    "Minimum Commitment": "Medium",
    "Audit Rights": "Medium",
    "Post-Termination Services": "Medium",
    "Renewal Term": "Medium",
    "Insurance": "Medium",
    "Warranty Duration": "Medium",
    "Source Code Escrow": "Medium",
    "Price Restrictions": "Medium",
    "No-Solicit Of Employees": "Medium",
    "No-Solicit Of Customers": "Medium",
    "Rofr/Rofo/Rofn": "Medium",
    "Irrevocable Or Perpetual License": "Medium",
    "Unlimited/All-You-Can-Eat-License": "Medium",
    "Affiliate License-Licensee": "Medium",
    "Affiliate License-Licensor": "Medium",

    # 🟢 LOW RISK — informational / structural
    "Governing Law": "Low",
    "Expiration Date": "Low",
    "Effective Date": "Low",
    "Agreement Date": "Low",
    "Notice Period To Terminate Renewal": "Low",
    "Parties": "Low",
    "Document Name": "Low",
    "License Grant": "Low",
    "Anti-Assignment": "Low",
    "Non-Transferable License": "Low",
    "Third Party Beneficiary": "Low"
}

### Apply Risk Labels

In [12]:
df["risk_level"] = df["clean_clause"].map(risk_map)

df[["clean_clause", "risk_level"]].head(10)

              clean_clause risk_level
0           Effective Date        Low
1          Expiration Date        Low
2             Renewal Term     Medium
3            Governing Law        Low
4              Exclusivity       High
5  No-Solicit Of Customers     Medium
6  No-Solicit Of Employees     Medium
7           Rofr/Rofo/Rofn     Medium
8          Anti-Assignment        Low
9       Price Restrictions     Medium

### Save  dataset

In [14]:
df_final = df[["clause_text", "clean_clause", "risk_level"]]

df_final.to_csv("../data/processed/cuad_risk_dataset.csv", index=False)

df_final.head()

,clause_text,clean_clause,risk_level
0,The term of this Agreement shall be ten (10)...,Effective Date,Low
1,The term of this Agreement shall be ten (10)...,Expiration Date,Low
2,If Distributor comp...,Renewal Term,Medium
3,This Agreement is to be construed according to...,Governing Law,Low
4,The Distributor shall not order or ...,Exclusivity,High